-- Insert test campeonato
INSERT INTO campeonatos (
    nombre,
    categoria,
    tipo,
    estado,
    fecha_inicio,
    fecha_fin,
    organizador,
    contacto,
    ciudad,
    provincia,
    direccion,
    estadio,
    hora_inicio,
    hora_fin,
    dias_juego,
    nivel_dificultad,
    numero_equipos,
    formato,
    fecha_creacion
) VALUES (
    'Copa Perú 2026',
    'Primera División',
    'Liga',
    'PROGRAMADO',
    '2026-04-15',
    '2026-12-31',
    'SIDAF Puno',
    'contacto@sidafpuno.pe',
    'Puno',
    'Puno',
    'Estadio Enrique Torres Beltrán',
    'Estadio ETB',
    '15:00',
    '18:00',
    'sábado,domingo',
    'Alto',
    13,
    'League',
    CURRENT_DATE
);
