package com.sidaf.backend.model;

public enum TipoEvento {
    PARTIDO_CREADO,
    PARTIDO_INICIADO,
    PARTIDO_FINALIZADO,
    PARTIDO_HOMOLOGADO,
    DESIGNACION_CREADA,
    DESIGNACION_PUBLICADA,
    DESIGNACION_CONFIRMADA,
    DESIGNACION_CANCELADA,
    ETAPA_CREADA,
    ETAPA_INICIADA,
    ETAPA_FINALIZADA,
    CAMPEONATO_CREADO,
    CAMPEONATO_INICIADO,
    CAMPEONATO_FINALIZADO,
    CAMPEONATO_CANCELADO,
    ARBITRO_REGISTRADO,
    ARBITRO_ACTUALIZADO,
    ARBITRO_DADO_BAJA,
    EQUIPO_REGISTRADO,
    EQUIPO_ACTUALIZADO,
    EQUIPO_ELIMINADO,
    EVALUACION_REGISTRADA,
    OBSERVACION_REGISTRADA,
    RESULTADO_REGISTRADO
}
